### ISSUE TITLE
Создание курсов для работы с данными в БД. Продумать workflow работы по старту курса

### ISSUE THREAD

**Issue by akostrikov** [manytask/manytask#216]

**Comment by zhmurov** [comment]
# Instructions I wrote to myself, which can be used here 
 
- SSH to manytask web server as root, cd /srv/manytask/. There, create a unique course folder. Use the same name as your are planning to use as domain name. In this folder, you need two files: docker-compose.yml and .env

docker-compose.yml:

version: "3.8"

```yaml
volumes:
    cache:
    solutions:

services:
    manytask:
        image: manytask/manytask:0.8.1
        container_name: manytask-qpython
        restart: always
        network_mode: bridge
        expose:
            - "5050"
        env_file: .env
        environment:
            VIRTUAL_HOST: qpython.manytask.org
            VIRTUAL_PORT: 5050
            LETSENCRYPT_HOST: qpython.manytask.org
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:5050/healthcheck" ]
            interval: 1m
            timeout: 15s
            retries: 3
            start_period: 30s
        volumes:
            - cache:/cache
            - solutions:/solutions
```

- .env file:

```yaml
FLASK_SECRET_KEY=[Generate any token]

# tokens
REGISTRATION_SECRET=[Generate any secret]
TESTER_TOKEN=[Generate any token]

# gitlab
GITLAB_URL=https://gitlab.manytask.org
GITLAB_ADMIN_TOKEN=[Create admin token here https://gitlab.manytask.org/-/user_settings/personal_access_tokens, scopes api, read_api, read_user, read_repository, write_repository, read_registry, write_registry, sudo, admin_mode]
GITLAB_COURSE_GROUP=quantum/python
GITLAB_COURSE_PUBLIC_REPO=quantum/python/public-2024-fall
GITLAB_COURSE_STUDENTS_GROUP=quantum/python/students-2024-fall
GITLAB_DEFAULT_BRANCH=main
GITLAB_CLIENT_ID=[Create application here https://gitlab.manytask.org/admin/applications, redirect url https://qpython.manytask.org/login_finish, trusted, scopes api, read_user, sudo, openid, profile, email]
GITLAB_CLIENT_SECRET=[Create application here https://gitlab.manytask.org/admin/applications]

# google sheets
GDOC_URL=https://docs.google.com
GDOC_ACCOUNT_CREDENTIALS_BASE64=[Your JSON Google service account token, converted to base64]
GDOC_SPREADSHEET_ID=[Copy Google sheet id from url]
GDOC_SCOREBOARD_SHEET=0
```

- Set the ``FLASK_SECRET_KEY`` and ``TESTER_TOKEN`` to two deferent random tokens. To create random token one can use the following script:

```bash
    head -c 12 /dev/urandom | shasum | cut -d ' ' -f
```
- Set the course registration secret. You can use e.g. chat GPT, by asking "Generate two-word pun about ..."

- In Admin Area (https://gitlab.manytask.org/admin/applications), create an application. Redirect to https://qpython.manytask.org/login_finish , make it trusted, add following scopes: api, read_user, sudo, openid, profile, email. Copy application credentials to ```GITLAB_CLIENT_ID```, ```GITLAB_CLIENT_SECRET``` in .env.

- Create admin token in https://gitlab.manytask.org/-/user_settings/personal_access_tokens with the folowing scopes api, read_api, read_user, read_repository, write_repository, read_registry, write_registry, sudo, admin_mode . Copy token to ```GITLAB_ADMIN_TOKEN``` in .env file.

- Create service account and export its credentials. Convert them to base 64, e.g. using the following python script:

```python
    import sys
    import json
    import base64


    with open(sys.argv[1]) as jsonfile:
        data = json.load(jsonfile)
        datastr = json.dumps(data)
        print(base64.b64encode(datastr.encode('utf-8')))
```

- Copy the result into ```GDOC_ACCOUNT_CREDENTIALS_BASE64``` in .env file

- Create an empty spreadsheet, name is using pattern "CourseFor CourseName Year Semester Scores" (e.g. Quantum Python 2024 Fall Scores). Share the shpreadsheet with the Google service account as editon, and with link as viewer. Copy the spreadsheet ID into ``GDOC_SPREADSHEET_ID`` of the .env file

- Set environment variable ```TESTER_TOKEN``` in your public repo, e.g. https://gitlab.manytask.org/quantum/python/public-2024-fall/-/settings/ci_cd

- Go to gitlab.manytask.org, generate public group for the course (e.g. quantum/python). In this group, create public repo for the course (e.g. public-2024-fall) and private group for the sudents repo (e.g. students-2024-fall). Use naming convesions so that it will be easier to set up private/public repositories later.


- Start the manytask docker:

```bash
docker compose -f docker-compose.yml up -d
```

- See logs:

```bash
docker compose -f docker-compose.yml logs -f
```

- See if the container already running:

```bash
docker compose -f docker-compose.yml ps
```

- Shutdown:

```bash
docker compose -f docker-compose.yml down
```
